import {
    dis2,
    dis3,
    dis4,
    dis5,
    dis6,
    dis7,
    dis8,
    dis9,
    dis10,
    dis11,
    dis12,
    dis13,
    dis15,
    dis16,
    dis2a,
    dis3a,
    dis4a,
    dis5a,
    dis6a,
    dis7a,
    dis8a,
    dis9a,
    dis10a,
    dis11a,
    dis12a,
    dis13a,
    dis15a,
    dis16a,
} from '../assets/piscinas';

export const ImgDesignPiscinas = [
    { id: 1, image: dis2, imageHover: dis2a, alt: 'Piscina' },
    { id: 6, image: dis6, imageHover: dis6a, alt: 'Piscina' },
    { id: 13, image: dis13, imageHover: dis13a, alt: 'Piscina' },
    { id: 10, image: dis10, imageHover: dis10a, alt: 'Piscina' },
    { id: 4, image: dis4, imageHover: dis4a, alt: 'Piscina' },
    { id: 9, image: dis9, imageHover: dis9a, alt: 'Piscina' },
    { id: 5, image: dis5, imageHover: dis5a, alt: 'Piscina' },
    { id: 8, image: dis8, imageHover: dis8a, alt: 'Piscina' },
    { id: 12, image: dis12, imageHover: dis12a, alt: 'Piscina' },
    { id: 15, image: dis15, imageHover: dis15a, alt: 'Piscina' },
    { id: 7, image: dis7, imageHover: dis7a, alt: 'Piscina' },
    { id: 2, image: dis3, imageHover: dis3a, alt: 'Piscina' },
    { id: 16, image: dis16, imageHover: dis16a, alt: 'Piscina' },
    { id: 11, image: dis11, imageHover: dis11a, alt: 'Piscina' },
];
